"""cards become encrypted autofill records

Revision ID: a1c9f4e82d07
Revises: 3f7a92c15d84
Create Date: 2026-08-11 10:15:00.000000

⚠ **Destructive.** ``customer_cards`` is dropped and recreated: nearly every
column changes shape (D7 revised — a card is now a local autofill record whose
number is stored AES-GCM encrypted, not a provider token), and no data can be
migrated because the old rows hold provider tokens that are worthless under the
new model. Acceptable pre-production; any saved rows are discarded.

Clients upgrade on their own schedule and may skip versions (PROJECT.md D10):
keep this revision self-contained and make ``downgrade`` real, not a ``pass``.

The CHECK constraints are **hand-written and cannot be autogenerated** —
``migrations/env.py::_include_object`` filters CHECK constraints out of
autogenerate. The partial unique index is hand-written because it must exclude
soft-deleted rows.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = 'a1c9f4e82d07'
down_revision: str | None = '3f7a92c15d84'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Old shapes, for ``downgrade`` — declaration order of the removed enums.
_CARD_STATUSES = ('pending_verification', 'active', 'removed', 'expired')
_PROVIDER_CODES = ('payme', 'click')


def _drop_old_table() -> None:
    op.drop_table('customer_cards')


def upgrade() -> None:
    _drop_old_table()
    op.create_table(
        'customer_cards',
        sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
        # No FK to ``customers``: cross-module reference (ARCHITECTURE.md §4).
        sa.Column('customer_id', sa.UUID(as_uuid=True), nullable=False),
        # AES-GCM ciphertext of the card number itself — never plaintext.
        # Nullable: deletion clears the ciphertext and keeps the row.
        sa.Column('pan', sa.Text(), nullable=True),
        sa.Column('key_version', sa.Integer(), nullable=True),
        sa.Column('masked_pan', sa.String(length=32), nullable=False),
        sa.Column('last4', sa.String(length=4), nullable=False),
        sa.Column('bin', sa.String(length=8), nullable=False),
        sa.Column('brand', sa.String(length=24), nullable=True),
        sa.Column('expiry_month', sa.SmallInteger(), nullable=False),
        sa.Column('expiry_year', sa.SmallInteger(), nullable=False),
        sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_cards')),
    )
    op.create_index(
        op.f('ix_customer_cards_customer_id'),
        'customer_cards',
        ['customer_id'],
    )
    op.create_index(
        op.f('ix_customer_cards_deleted_at'),
        'customer_cards',
        ['deleted_at'],
    )
    # One card saved once — keyed on the masked identity, deliberately not on
    # anything derived from the real number (the ciphertext cannot be a key:
    # AES-GCM's random nonce encrypts the same number differently every time).
    op.create_index(
        'uq_customer_cards_identity_live',
        'customer_cards',
        ['customer_id', 'masked_pan', 'expiry_month', 'expiry_year'],
        unique=True,
        postgresql_where=sa.text('deleted_at IS NULL'),
    )
    op.create_check_constraint(
        op.f('ck_customer_cards_expiry_month_range'),
        'customer_cards',
        'expiry_month BETWEEN 1 AND 12',
    )
    # A live row always holds ciphertext, a deleted row never does.
    op.create_check_constraint(
        op.f('ck_customer_cards_deleted_has_no_pan'),
        'customer_cards',
        '(deleted_at IS NULL) = (pan IS NOT NULL)',
    )


def downgrade() -> None:
    # Recreates the token-flow shape of revision 4e7c02b915da verbatim. The
    # rows created under the new model are discarded — equally destructive in
    # this direction, for the same reason: the two shapes share no usable data.
    op.drop_table('customer_cards')
    op.create_table(
        'customer_cards',
        sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('customer_id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column(
            'provider',
            sa.Enum(
                *_PROVIDER_CODES,
                name='payment_provider_code',
                native_enum=False,
                create_constraint=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            'status',
            sa.Enum(
                *_CARD_STATUSES,
                name='card_status',
                native_enum=False,
                create_constraint=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column('token', sa.Text(), nullable=True),
        sa.Column('key_version', sa.Integer(), nullable=True),
        sa.Column('masked_pan', sa.String(length=32), nullable=False),
        sa.Column('last4', sa.String(length=4), nullable=False),
        sa.Column('bin', sa.String(length=8), nullable=True),
        sa.Column('brand', sa.String(length=24), nullable=True),
        sa.Column('expiry_month', sa.SmallInteger(), nullable=True),
        sa.Column('expiry_year', sa.SmallInteger(), nullable=True),
        sa.Column('label', sa.String(length=64), nullable=True),
        sa.Column(
            'is_default',
            sa.Boolean(),
            server_default=sa.text('false'),
            nullable=False,
        ),
        sa.Column('phone_masked', sa.String(length=32), nullable=True),
        sa.Column(
            'verify_attempts',
            sa.Integer(),
            server_default=sa.text('0'),
            nullable=False,
        ),
        sa.Column('otp_sent_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_cards')),
    )
    op.create_index(
        op.f('ix_customer_cards_customer_id'), 'customer_cards', ['customer_id']
    )
    op.create_index(
        op.f('ix_customer_cards_deleted_at'), 'customer_cards', ['deleted_at']
    )
    op.create_index(
        'uq_customer_cards_default_live',
        'customer_cards',
        ['customer_id'],
        unique=True,
        postgresql_where=sa.text('is_default AND deleted_at IS NULL'),
    )
    op.create_index(
        'uq_customer_cards_identity_live',
        'customer_cards',
        ['customer_id', 'provider', 'masked_pan', 'expiry_month', 'expiry_year'],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND status = 'active'"),
    )
    _statuses = ', '.join(f"'{value}'" for value in _CARD_STATUSES)
    _codes = ', '.join(f"'{value}'" for value in _PROVIDER_CODES)
    op.create_check_constraint(
        op.f('ck_customer_cards_card_status'),
        'customer_cards',
        f'status IN ({_statuses})',
    )
    op.create_check_constraint(
        op.f('ck_customer_cards_payment_provider_code'),
        'customer_cards',
        f'provider IN ({_codes})',
    )
    op.create_check_constraint(
        op.f('ck_customer_cards_expiry_month_range'),
        'customer_cards',
        'expiry_month IS NULL OR expiry_month BETWEEN 1 AND 12',
    )
    op.create_check_constraint(
        op.f('ck_customer_cards_verify_attempts_non_negative'),
        'customer_cards',
        'verify_attempts >= 0',
    )
    op.create_check_constraint(
        op.f('ck_customer_cards_removed_has_no_token'),
        'customer_cards',
        "status <> 'removed' OR token IS NULL",
    )
