"""customer saved cards

Revision ID: 4e7c02b915da
Revises: 2a9b860859f1
Create Date: 2026-08-10 18:30:00.000000

Clients upgrade on their own schedule and may skip versions (PROJECT.md D10):
keep this revision self-contained and make ``downgrade`` real, not a ``pass``.

Two CHECK constraints here are **hand-written and cannot be autogenerated** —
``card_status`` and ``payment_provider_code``, both rendered by SQLAlchemy from
an ``Enum(native_enum=False)``. ``migrations/env.py::_include_object`` filters
CHECK constraints out of autogenerate for the reason the avatar revision spells
out, so the DDL is written here by hand. The two partial unique indexes are
hand-written for a different reason: ``soft_delete_unique_index`` only emits
``WHERE deleted_at IS NULL``, and both of these need a second predicate.

No column holds a card number, in any form — not even a hash. See
``app/modules/payments/models.py``.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = '4e7c02b915da'
down_revision: str | None = '2a9b860859f1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Declaration order of ``CardStatus`` (app/providers/payments/base.py).
_CARD_STATUSES = ('pending_verification', 'active', 'removed', 'expired')
#: Declaration order of ``PaymentProviderCode``.
_PROVIDER_CODES = ('payme', 'click')


def upgrade() -> None:
    op.create_table(
        'customer_cards',
        sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
        # No FK to ``customers``: cross-module reference (ARCHITECTURE.md §4).
        sa.Column('customer_id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column(
            'provider',
            sa.Enum(
                *_PROVIDER_CODES,
                name='payment_provider_code',
                native_enum=False,
                create_constraint=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            'status',
            sa.Enum(
                *_CARD_STATUSES,
                name='card_status',
                native_enum=False,
                create_constraint=False,
                length=24,
            ),
            nullable=False,
        ),
        # AES-GCM ciphertext of the provider's token — never a card number.
        sa.Column('token', sa.Text(), nullable=True),
        sa.Column('key_version', sa.Integer(), nullable=True),
        sa.Column('masked_pan', sa.String(length=32), nullable=False),
        sa.Column('last4', sa.String(length=4), nullable=False),
        sa.Column('bin', sa.String(length=8), nullable=True),
        sa.Column('brand', sa.String(length=24), nullable=True),
        sa.Column('expiry_month', sa.SmallInteger(), nullable=True),
        sa.Column('expiry_year', sa.SmallInteger(), nullable=True),
        sa.Column('label', sa.String(length=64), nullable=True),
        sa.Column(
            'is_default',
            sa.Boolean(),
            server_default=sa.text('false'),
            nullable=False,
        ),
        sa.Column('phone_masked', sa.String(length=32), nullable=True),
        sa.Column(
            'verify_attempts',
            sa.Integer(),
            server_default=sa.text('0'),
            nullable=False,
        ),
        sa.Column('otp_sent_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_cards')),
    )
    op.create_index(
        op.f('ix_customer_cards_customer_id'),
        'customer_cards',
        ['customer_id'],
    )
    op.create_index(
        op.f('ix_customer_cards_deleted_at'),
        'customer_cards',
        ['deleted_at'],
    )

    # "Exactly one default" as a database guarantee, not a convention: two tabs
    # pressing the button in the same millisecond are two transactions that
    # cannot see each other.
    op.create_index(
        'uq_customer_cards_default_live',
        'customer_cards',
        ['customer_id'],
        unique=True,
        postgresql_where=sa.text('is_default AND deleted_at IS NULL'),
    )
    # One card saved once — keyed on the provider's masked string, deliberately
    # not on anything derived from the real number.
    op.create_index(
        'uq_customer_cards_identity_live',
        'customer_cards',
        ['customer_id', 'provider', 'masked_pan', 'expiry_month', 'expiry_year'],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND status = 'active'"),
    )

    _statuses = ', '.join(f"'{value}'" for value in _CARD_STATUSES)
    _codes = ', '.join(f"'{value}'" for value in _PROVIDER_CODES)
    op.create_check_constraint(
        op.f('ck_customer_cards_card_status'),
        'customer_cards',
        f'status IN ({_statuses})',
    )
    op.create_check_constraint(
        op.f('ck_customer_cards_payment_provider_code'),
        'customer_cards',
        f'provider IN ({_codes})',
    )
    op.create_check_constraint(
        op.f('ck_customer_cards_expiry_month_range'),
        'customer_cards',
        'expiry_month IS NULL OR expiry_month BETWEEN 1 AND 12',
    )
    op.create_check_constraint(
        op.f('ck_customer_cards_verify_attempts_non_negative'),
        'customer_cards',
        'verify_attempts >= 0',
    )
    # The belt to the service's braces: a removed card must not keep a usable
    # token, whichever code path removed it.
    op.create_check_constraint(
        op.f('ck_customer_cards_removed_has_no_token'),
        'customer_cards',
        "status <> 'removed' OR token IS NULL",
    )


def downgrade() -> None:
    op.drop_constraint(
        op.f('ck_customer_cards_removed_has_no_token'),
        'customer_cards',
        type_='check',
    )
    op.drop_constraint(
        op.f('ck_customer_cards_verify_attempts_non_negative'),
        'customer_cards',
        type_='check',
    )
    op.drop_constraint(
        op.f('ck_customer_cards_expiry_month_range'),
        'customer_cards',
        type_='check',
    )
    op.drop_constraint(
        op.f('ck_customer_cards_payment_provider_code'),
        'customer_cards',
        type_='check',
    )
    op.drop_constraint(
        op.f('ck_customer_cards_card_status'), 'customer_cards', type_='check'
    )
    op.drop_index('uq_customer_cards_identity_live', table_name='customer_cards')
    op.drop_index('uq_customer_cards_default_live', table_name='customer_cards')
    op.drop_index(op.f('ix_customer_cards_deleted_at'), table_name='customer_cards')
    op.drop_index(op.f('ix_customer_cards_customer_id'), table_name='customer_cards')
    op.drop_table('customer_cards')
