"""profile avatar and saved passengers

Revision ID: 96f1b68a3874
Revises: 8c64b732eb50
Create Date: 2026-08-06 16:36:15.310112

Clients upgrade on their own schedule and may skip versions (PROJECT.md D10):
keep this revision self-contained and make ``downgrade`` real, not a ``pass``.

The ``upload_purpose`` CHECK below is **hand-written and cannot be
autogenerated**. ``migrations/env.py::_include_object`` filters check
constraints out of autogenerate on purpose: SQLAlchemy renders an
``Enum(native_enum=False)`` as ``purpose IN (__[POSTCOMPILE_param_1])``, which
Alembic cannot compare against the server's ``= ANY (ARRAY[...])``, so it would
decide on every single revision that somebody had dropped the constraint. That
filter is why adding a member to ``UploadPurpose`` produces an empty
autogenerated diff, and why this revision spells the DDL out.

This is the first enum-CHECK rewrite in the chain; the shape here is the one to
copy next time.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = '96f1b68a3874'
down_revision: str | None = '8c64b732eb50'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Declaration order of ``UploadPurpose`` (app/providers/storage/base.py).
_PURPOSES_BEFORE = (
    'logo', 'favicon', 'app_icon', 'blog_cover', 'promo_banner', 'banner',
    'document', 'export',
)
_PURPOSES_AFTER = (*_PURPOSES_BEFORE, 'avatar')

#: Wrapped in ``op.f`` at every use site, which marks the name as already
#: final: without it the metadata naming convention
#: (``ck_%(table_name)s_%(constraint_name)s``) is applied on top and the name
#: becomes ``ck_uploads_ck_uploads_upload_purpose``. The wrapping cannot happen
#: here — ``op`` is a proxy that only exists while a migration is running, and
#: calling it at module level breaks every command that merely *loads* this
#: script, ``alembic heads`` included.
_PURPOSE_CHECK = 'ck_uploads_upload_purpose'


def _purpose_in(values: Sequence[str]) -> str:
    listed = ', '.join(f"'{value}'" for value in values)
    return f'purpose IN ({listed})'


def upgrade() -> None:
    op.create_table('passengers',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('document_type', sa.String(length=32), nullable=True),
    sa.Column('document_number', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_passengers_customer_id_customers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passengers'))
    )
    op.create_index(op.f('ix_passengers_customer_id'), 'passengers', ['customer_id'], unique=False)
    op.create_index(op.f('ix_passengers_deleted_at'), 'passengers', ['deleted_at'], unique=False)
    op.add_column('customers', sa.Column('avatar_id', sa.UUID(), nullable=True))

    op.drop_constraint(op.f(_PURPOSE_CHECK), 'uploads', type_='check')
    op.create_check_constraint(
        op.f(_PURPOSE_CHECK), 'uploads', _purpose_in(_PURPOSES_AFTER)
    )


def downgrade() -> None:
    # Any avatar already uploaded would violate the narrower constraint, so the
    # rows go before it is put back. The bytes on disk are left to the orphan
    # sweep rather than deleted from a migration, which has no storage adapter.
    op.execute("DELETE FROM uploads WHERE purpose = 'avatar'")
    op.drop_constraint(op.f(_PURPOSE_CHECK), 'uploads', type_='check')
    op.create_check_constraint(
        op.f(_PURPOSE_CHECK), 'uploads', _purpose_in(_PURPOSES_BEFORE)
    )

    op.drop_column('customers', 'avatar_id')
    op.drop_index(op.f('ix_passengers_deleted_at'), table_name='passengers')
    op.drop_index(op.f('ix_passengers_customer_id'), table_name='passengers')
    op.drop_table('passengers')
