"""avatar is a client side code

Revision ID: 8c1d4a6f2b70
Revises: 4e7c02b915da
Create Date: 2026-08-10 19:15:00.000000

Clients upgrade on their own schedule and may skip versions (PROJECT.md D10):
keep this revision self-contained and make ``downgrade`` real, not a ``pass``.

An avatar is no longer a file (API.md §19). The set of pictures ships with the
app and the site, the customer picks one, and the server keeps only the code:
``customers.avatar_id`` becomes ``VARCHAR(64)`` and the ``avatar`` upload
purpose goes with the endpoints that used it.

The ``upload_purpose`` CHECK below is **hand-written and cannot be
autogenerated** — ``migrations/env.py::_include_object`` filters check
constraints out of autogenerate, for the reason
``20260806_1636_profile_avatar_and_saved_passengers`` spells out.

Both directions lose something, and the comments at each site say what:
``upgrade`` cannot turn a stored file into a picture the client ships, and
``downgrade`` cannot turn a code into a file.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = '8c1d4a6f2b70'
down_revision: str | None = '4e7c02b915da'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Declaration order of ``UploadPurpose`` (app/providers/storage/base.py).
_PURPOSES_AFTER = (
    'logo', 'favicon', 'app_icon', 'blog_cover', 'promo_banner', 'banner',
    'document', 'export', 'payment_logo',
)
_PURPOSES_BEFORE = (*_PURPOSES_AFTER[:-1], 'avatar', 'payment_logo')

#: Wrapped in ``op.f`` at every use site — the naming convention would
#: otherwise prefix it a second time. Not wrapped here: ``op`` is a proxy that
#: only exists while a migration runs, so calling it at module level breaks
#: every command that merely loads this script, ``alembic heads`` included.
_PURPOSE_CHECK = 'ck_uploads_upload_purpose'


def _purpose_in(values: Sequence[str]) -> str:
    listed = ', '.join(f"'{value}'" for value in values)
    return f'purpose IN ({listed})'


def upgrade() -> None:
    # Uploaded avatars stop being referenced here, so the column is emptied
    # rather than cast: a UUID left in a text column would read as a picture
    # code no client has, and the client would render nothing for it anyway.
    # Customers pick again from the set their app ships.
    op.execute("UPDATE customers SET avatar_id = NULL WHERE avatar_id IS NOT NULL")
    op.alter_column(
        'customers',
        'avatar_id',
        existing_type=sa.dialects.postgresql.UUID(),
        type_=sa.String(length=64),
        existing_nullable=True,
        postgresql_using='avatar_id::text',
    )

    # The rows go before the narrower constraint does, as in the revision that
    # introduced them. The bytes on disk are left to the orphan sweep rather
    # than deleted from a migration, which has no storage adapter.
    op.execute("DELETE FROM uploads WHERE purpose = 'avatar'")
    op.drop_constraint(op.f(_PURPOSE_CHECK), 'uploads', type_='check')
    op.create_check_constraint(
        op.f(_PURPOSE_CHECK), 'uploads', _purpose_in(_PURPOSES_AFTER)
    )


def downgrade() -> None:
    op.drop_constraint(op.f(_PURPOSE_CHECK), 'uploads', type_='check')
    op.create_check_constraint(
        op.f(_PURPOSE_CHECK), 'uploads', _purpose_in(_PURPOSES_BEFORE)
    )

    # A picture code is not an upload id and there is no file to point the
    # column back at, so it is emptied before the type narrows — the cast would
    # fail on the first code otherwise, and failing here would leave an
    # installation unable to go back at all.
    op.execute("UPDATE customers SET avatar_id = NULL WHERE avatar_id IS NOT NULL")
    op.alter_column(
        'customers',
        'avatar_id',
        existing_type=sa.String(length=64),
        type_=sa.dialects.postgresql.UUID(),
        existing_nullable=True,
        postgresql_using='avatar_id::uuid',
    )
